name = "vacation-manager-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "vacation-manager-db"
database_id = "5a074db9-2e92-411c-98ba-a6859f5524f3"

[vars]
ENVIRONMENT = "development"